### ISSUE TITLE
Game version text

### ISSUE THREAD

**Issue by ArtjomsBrovkins** [TiagoXavi/topdrives-records#1]
It would be great to have a game version text in these places:

- [ ] Somewhere on a page header
![image](https://user-images.githubusercontent.com/2305517/184921672-48533cdc-8dd2-43d3-85bc-dffbbc5a1a0f.png)
- [ ] When exporting the image in the same place

**Comment by TiagoXavi** [comment]
I have some questions. This will be a fixed text? If yes, that's easy.
But if the version need to be related to every time inputted, so it will be a bit complex

**Comment by ArtjomsBrovkins** [comment]
Static text with actual version of the game. Most likely something similar to solution form this
https://stackoverflow.com/questions/40167639/how-to-get-application-version-from-google-play

**Comment by TiagoXavi** [comment]
Wow, too much automated. For now I just inserted a fixed text. Hutch the game don't update too often. We can manually edit it for now. Commit 0556860
