### ISSUE TITLE
Campaign tracks mapper

### ISSUE THREAD

**Issue by ArtjomsBrovkins** [TiagoXavi/topdrives-records#4]
Can you do something like when you hover over 1/2 mile it shows you where it is in campaign?

Raw track collection is ready
https://docs.google.com/spreadsheets/d/1hEzdps4oMPkYGbTJvdpL4J9ZZFenG9N1C_Yo9Qc4VF0/edit?usp=sharing

**Comment by LiamCavens** [comment]
I've done this I just need rights to push

**Comment by ArtjomsBrovkins** [comment]
#12 should have fixed this
